[package]
name = "unrar"
version = "0.1.0"
authors = ["Danyel Bayraktar <danyel@webhippie.de>"]

license = "MIT"
description = "list and extract RAR archives"
repository = "https://github.com/muja/unrar.rs"

[dependencies]
libc = "0.1"
regex = "0.1.8"
lazy_static = "0.1.12"
enum_primitive = "*"
num = "*"

[dependencies.unrar_sys]
path = "unrar_sys"
version = "0.1"
